#!/usr/bin/env sh

. /etc/log2ram.conf

HDD_LOG=/var/log.bak
OLD_LOG=/var/log.old
RAM_LOG=/var/log

LOG_NAME="log2ram.log"
LOG2RAM_LOG="${RAM_LOG}/${LOG_NAME}"

isSafe () {
    [ -d $HDD_LOG/ ] || echo "ERROR: $HDD_LOG/ doesn't exist! Can't sync."
    [ -d $HDD_LOG/ ] || exit 1
}

syncToDisk () {
    isSafe

    if [ "$USE_RSYNC" = true ]; then
        rsync -aXv --inplace --no-whole-file --delete --links $RAM_LOG/ $HDD_LOG/ 2>&1
        # TODO confirm the best rsync command by running some comparision tests
        # See https://community.openenergymonitor.org/t/emonsd-next-steps-filesystem/10693/54?u=pb66
        #rsync -aXWv --delete --links $RAM_LOG/ $HDD_LOG/ 2>&1 | $LOG_OUTPUT
    else
        cp -rfup $RAM_LOG/ -T $HDD_LOG/ 2>&1
    fi
}

syncFromDisk () {
    isSafe

    if [ ! -z "$(du -sh -t "$SIZE" $HDD_LOG/ | cut -f1)" ]; then
        echo "ERROR: RAM disk too small. Can't sync."
        umount -l $RAM_LOG/
        umount -l $HDD_LOG/
        if [ "$MAIL" = true ]; then
            echo "LOG2RAM : No place on RAM anymore, fallback on the disk" | mail -s 'Log2Ram Error' root;
        fi
        exit 1
    fi

    if [ "$USE_RSYNC" = true ]; then
        rsync -aXWv --delete --links $HDD_LOG/ $RAM_LOG/ 2>&1
    else
        cp -rfup $HDD_LOG/ -T $RAM_LOG/ 2>&1
    fi
}

wait_for () {
    while ! grep -qs "$1" /proc/mounts; do
        sleep 0.1
    done
}

case "$1" in
  start)
      [ -d $HDD_LOG/ ] || mkdir $HDD_LOG/
      mount --bind $RAM_LOG/ $HDD_LOG/
      mount --make-private $HDD_LOG/
      wait_for $HDD_LOG
      mount -t tmpfs -o nosuid,noexec,nodev,mode=0755,size="$SIZE" log2ram $RAM_LOG/
      wait_for $RAM_LOG
      syncFromDisk
      [ -d $RAM_LOG/rotated_logs ] || ln -s $OLD_LOG $RAM_LOG/rotated_logs
      ;;

  stop)
      syncToDisk
      umount -l $RAM_LOG/
      umount -l $HDD_LOG/
      ;;

  write)
      syncToDisk
      ;;

  *)
      echo "Usage: log2ram {start|stop|write}" >&2
      exit 1
      ;;
esac
